[package]
name = "raytracer"
version = "0.1.0"
authors = ["Matt"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_dispatch = "0.3.0"
rand = "0.7.3"
rayon = "*"
indicatif = {version = "*", features = ["with_rayon"]}
